---- RELATIONSHIP IN SQL ----

/*
THERE ARE FOUR TYPES OF RELATIONSHIPS IN SQL.

1. ONE TO ONE (1:1)
   - EK RECORD KA SIRF EK HI RELATED RECORD HOTA HAI.

- EXAMPLE:
    
	EK PERSON KE PAAS SIRF EK PASSPORT HOTA HAI,
     AUR EK PASSPORT SIRF EK PERSON KA HOTA HAI.


2. ONE TO MANY (1:M)
   - EK RECORD KE SAATH KAI RECORDS CONNECT HO SAKTE HAIN.
   
   - EXAMPLE:
   
   EK TEACHER KAI STUDENTS KO PADHA SAKTA HAI,
     LEKIN HAR STUDENT KA EK HI CLASS TEACHER HAI.


3. MANY TO ONE (M:1)
   - KAI RECORDS EK HI RECORD SE CONNECT HOTE HAIN.
  
  - EXAMPLE:
     
	 KAI EMPLOYEES EK HI DEPARTMENT MEIN KAAM KAR SAKTE HAIN,
     LEKIN HAR EMPLOYEE SIRF EK DEPARTMENT SE BELONG KARTA HAI.



4. MANY TO MANY (M:M)
   - KAI RECORDS KAI RECORDS SE CONNECT HO SAKTE HAIN.
  
  - EXAMPLE:
    
	EK STUDENT KAI COURSES MEIN ENROLL HO SAKTA HAI,
     AUR EK COURSE MEIN KAI STUDENTS ENROLL HO SAKTE HAIN.
*/

/*
NOTE:
- ONE TO ONE RELATIONSHIP MEIN AKSAR DONO TABLES KE PRIMARY KEY YA UNIQUE KEY KA USE HOTA HAI.

- ONE TO MANY AUR MANY TO ONE RELATIONSHIP KO FOREIGN KEY KE THROUGH IMPLEMENT KIYA JATA HAI.

- MANY TO MANY RELATIONSHIP KO DIRECTLY IMPLEMENT NAHI KIYA JATA.
  ISKE LIYE EK JUNCTION (INTERMEDIATE/BRIDGE) TABLE BANAI JATI HAI.
*/


CREATE TABLE STUDENT (
STUDENT_ID SERIAL PRIMARY KEY,
NAME VARCHAR(100)NOT NULL
);

INSERT INTO STUDENT (NAME)
VALUES ('RIYA'),
('PRASHANT'),
('SRISHTI');


SELECT * FROM STUDENT;


CREATE TABLE STUDENT_PROFILES(
STUDENT_ID INT PRIMARY KEY,
ADDRESS TEXT ,
AGE INT,
PHONE VARCHAR (15)
);


INSERT INTO STUDENT_PROFILES (STUDENT_ID , ADDRESS , AGE,PHONE)
VALUES
(1 , 'NOIDA', 18 , '1234567899'),
(2 , 'NOIDA', 17 , '1334567899'),
(3 , 'UK', 12 , '1235567899');

SELECT * FROM STUDENT_PROFILES;

ALTER TABLE STUDENT_PROFILES
ADD CONSTRAINT FK_STUDENT_ID
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID);

--ONE TO ONE RELATIONSHIP---
--MARKS TABLE--
CREATE TABLE MARKS (
MARKS_ID SERIAL PRIMARY KEY,
STUDENT_ID INT,
SUBJECT VARCHAR(50),
MARKS INT,
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);


INSERT INTO MARKS(STUDENT_ID , SUBJECT ,MARKS)
VALUES
(1 , 'ENGLISH' ,80),
(1 , 'MATH' ,75),
(1 , 'SCIENCE' ,91),

(2 , 'ENGLISH' ,82),
(2 , 'MATH' ,83),
(2 , 'SCIENCE' ,79),

(3 , 'ENGLISH' ,92),
(3 , 'MATH' ,73),
(3 , 'SCIENCE' ,89);

SELECT * FROM MARKS;


 


